### PR TITLE
Add config flow

### PR DESCRIPTION
**Pull request by starkillerOG**
add config flow to the goodwe integration as a step towards an official HomeAssistant integration.

~This is still a work in progress, DO NOT MERGE YET!~
To do:
- ~add DataUpdateCoordinator instead of refresh job~
- ~clean up code (black, isort, pylint, flake8, pydocstyle) and fix imports etc.~
- test the code

### CODE REVIEW

**Comment by starkillerOG** [comment]
The new new inverter_class field is used in the config flow on line 84 to extract the inverter family/class that is discovered during the first connection (in which the family/class is not provided and auto discovery is used).
That information is then saved in the config data and on all normal starts of the integration (restart HomeAssistant etc.) this data is used to supply the family/class on line 36 of the __init__ file, in that way on normal starts no time is wasted on trying to determine the correct family/class.

**Comment by mletenay** [comment]
Aaah I see.
But thinking, couldn't we use `type(inverter).__name__ ` instead of additional instance attribute ?

**Comment by starkillerOG** [comment]
@mletenay you are probably right, I will change it

**Comment by starkillerOG** [comment]
@mletenay I think the code of this PR is ready, the config flow is implemented, a DataUpdateCoordinator is implemented and everything is formatted and the imports are checked.

Could you give it a try and see if it actually works?
(I can't test it myself since I don't own a Goodwe inverter yet)

**Comment by mletenay** [comment]
Great !
The code looks fine, I'll test it today evening and merge it if everything works as expected.

**Comment by mletenay** [comment]
I did not manage to find enough time for this tonight, did just brief testing, but everything seems to be fine so far !
Will review and merge it on Wednesday ...

**Comment by mletenay** [comment]
Thanks, I have merged to PR (and than fixed some minor string typos).
It works nice, but we lost during this change the code created here https://github.com/mletenay/home-assistant-goodwe-inverter/commit/239e54f7a100a23a98c00dbb6d520d9a7d28cea5 around line 186.
It was added there just recently to address  unreliability of the UDP protocol where requests are rather frequently lost in some environments. And that piece of code was actually ignoring first 3 missed/lost packets and reset the sensors to None only after 4 consecutive packet failure.
How should we implement this behavior after we switched to DataUpateCoordinator ?

**Comment by starkillerOG** [comment]
@mletenay I think the packet loss schould be dealt with in the upstream library where we schould just retry the update command after a resonable timeout for up to 3/4 times.
However if you would really want to, you could still implement a simular code to make a couple of retries inside the async_update_data() function here: https://github.com/mletenay/home-assistant-goodwe-inverter/blob/9d630b9e195dc1f71e156e321c8d4c2c1f55aadf/custom_components/goodwe/__init__.py#L46

Or if you don't want to retry emidatly and wait for the next scan_interval, you could overwrite the `available` property of the sensor classes and make up your own available logic by adding a "failed_attempts" key to the data in async_update_data() that can count how many times the requests have failed, and based on that mark the device as available/unavailable.

**Comment by starkillerOG** [comment]
Why did you remove the device_info from the sensor entities?
Schouldn't all those entities be linked to the single device entry for the inverter?

**Comment by starkillerOG** [comment]
Very glad to hear that the code is actually working on a real Goodwe inverter.
Actually was not expecting it to work on the first try ;)

**Comment by mletenay** [comment]
It worked like a charm on first run, well done !
I have removed the device info from the individual sensors an left it only on the main entity, since the sensor device info was actually being overwritten over and over and there was at the end only device info of the last sensor.
I was probably consequence of the `"identifiers": {(DOMAIN, self._config_entry.unique_id)}`, be all the same for all sensors ?
Or maybe just the `"name": self.name,` should be fixed/static for all the sensors ?

**Comment by mletenay** [comment]
Regarding the UDP retries, the library performs (3) retries already. The code in sensors was additional on top of that.
If from some reason connection to inverter got lost and all the requests fail, we want to set sensor values to None to actually see/record the problem. But there are people out there with occasional/random dropouts (larger than the standard library retry mechanism). And for those we intentionally keep (stale) sensor values for couple of scan_intervals till its set to None.

**Comment by starkillerOG** [comment]
yea indeed the name schould be constant and schould be the name of the device aka the inverter, not from the entities.

**Comment by starkillerOG** [comment]
You could also use `self._config_entry.title` instead of the constant default name.
But honestly it does not really matter since users can overwrite the name anyway though the UI.

**Comment by mletenay** [comment]
I'll try the "available" property approach, it's actually what I tried to achieve with that clumsy retry counting.
My knowledge of HA internal is pretty shallow, so I just did the simplest way I've imaged ;-)

**Comment by starkillerOG** [comment]
> 
> 
> Regarding the UDP retries, the library performs (3) retries already. The code in sensors was additional on top of that.
> If from some reason connection to inverter got lost and all the requests fail, we want to set sensor values to None to actually see/record the problem. But there are people out there with occasional/random dropouts (larger than the standard library retry mechanism). And for those we intentionally keep (stale) sensor values for couple of scan_intervals till its set to None.

I think the best approach would then be to overwrite the available property and keep track of the amount of request tries

**Comment by starkillerOG** [comment]
I am not sure if we have acces to the previous "data" dict when running the next `async_update_data()`, which is needed to increment the retry counter.
Therfore it might be nessesary to implement the retry counter in the upstream lib as part of the inverter class.

**Comment by mletenay** [comment]
Actually a good idea, I will pass the number of consecutive retry failures inside the MaxRetriesException raised by the library and handle that one in `async_update_data()`

**Pull request merged**
